# Generated by Django 5.1.2 on 2024-11-18 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggriculturalOfficer',
            fields=[
                ('aid', models.OneToOneField(db_column='AID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='myapp.user')),
            ],
            options={
                'db_table': 'aggricultural_officer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DidPidRidNid',
            fields=[
                ('did', models.OneToOneField(db_column='did', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='myapp.user')),
                ('pid', models.IntegerField()),
                ('rid', models.IntegerField()),
            ],
            options={
                'db_table': 'did_pid_rid_nid',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DinsributorCompany',
            fields=[
                ('did', models.OneToOneField(db_column='DID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='myapp.user')),
            ],
            options={
                'db_table': 'dinsributor_company',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pid', models.AutoField(db_column='PID', primary_key=True, serialize=False)),
                ('pfastname', models.CharField(blank=True, db_column='PFastName', max_length=100, null=True)),
                ('plastname', models.CharField(blank=True, db_column='PLastName', max_length=100, null=True)),
                ('weight', models.DecimalField(blank=True, db_column='Weight', decimal_places=2, max_digits=10, null=True)),
                ('unitprice', models.DecimalField(blank=True, db_column='UnitPrice', decimal_places=2, max_digits=10, null=True)),
                ('exday', models.IntegerField(blank=True, db_column='ExDay', null=True)),
                ('exm', models.IntegerField(blank=True, db_column='ExM', null=True)),
                ('exy', models.IntegerField(blank=True, db_column='ExY', null=True)),
                ('tem', models.DecimalField(blank=True, db_column='TEM', decimal_places=2, max_digits=5, null=True)),
                ('humidity', models.DecimalField(blank=True, db_column='Humidity', decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('fid', models.OneToOneField(db_column='FID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='myapp.user')),
            ],
            options={
                'db_table': 'farmer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('harvest_id', models.AutoField(db_column='Harvest_Id', primary_key=True, serialize=False)),
                ('crop_type', models.CharField(blank=True, max_length=255, null=True)),
                ('hd', models.IntegerField(blank=True, db_column='HD', null=True)),
                ('hm', models.IntegerField(blank=True, db_column='HM', null=True)),
                ('hy', models.IntegerField(blank=True, db_column='HY', null=True)),
                ('quantity', models.DecimalField(blank=True, db_column='Quantity', decimal_places=2, max_digits=10, null=True)),
                ('hcity', models.CharField(blank=True, db_column='Hcity', max_length=255, null=True)),
                ('harea', models.CharField(blank=True, db_column='Harea', max_length=255, null=True)),
                ('hstreet', models.CharField(blank=True, db_column='Hstreet', max_length=255, null=True)),
            ],
            options={
                'db_table': 'harvest',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Neutroshonist',
            fields=[
                ('nid', models.OneToOneField(db_column='NID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='myapp.user')),
            ],
            options={
                'db_table': 'neutroshonist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Samplingresult',
            fields=[
                ('resultid', models.AutoField(db_column='ResultID', primary_key=True, serialize=False)),
                ('ed', models.IntegerField(blank=True, db_column='ED', null=True)),
                ('em', models.IntegerField(blank=True, db_column='EM', null=True)),
                ('ey', models.IntegerField(blank=True, db_column='EY', null=True)),
                ('humidity', models.DecimalField(blank=True, db_column='Humidity', decimal_places=2, max_digits=5, null=True)),
                ('temptostore', models.DecimalField(blank=True, db_column='TempToStore', decimal_places=2, max_digits=5, null=True)),
                ('resultsali', models.CharField(blank=True, db_column='ResultSaLi', max_length=100, null=True)),
                ('rminute', models.IntegerField(blank=True, db_column='RMinute', null=True)),
                ('rhour', models.IntegerField(blank=True, db_column='RHour', null=True)),
                ('rday', models.IntegerField(blank=True, db_column='RDay', null=True)),
                ('rmonth', models.IntegerField(blank=True, db_column='RMonth', null=True)),
                ('ryear', models.IntegerField(blank=True, db_column='RYear', null=True)),
            ],
            options={
                'db_table': 'samplingresult',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wirehousemanager',
            fields=[
                ('wid', models.OneToOneField(db_column='WID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='myapp.user')),
            ],
            options={
                'db_table': 'wirehousemanager',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Distributorcompanydemand',
            fields=[
                ('quantity', models.IntegerField(blank=True, db_column='Quantity', null=True)),
                ('price', models.DecimalField(blank=True, db_column='Price', decimal_places=2, max_digits=10, null=True)),
                ('pid', models.OneToOneField(db_column='PID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='myapp.product')),
            ],
            options={
                'db_table': 'distributorcompanydemand',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productbuydistributorcompany',
            fields=[
                ('pid', models.OneToOneField(db_column='PID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='myapp.product')),
                ('price', models.DecimalField(blank=True, db_column='PRICE', decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.IntegerField(blank=True, db_column='QUANTITY', null=True)),
            ],
            options={
                'db_table': 'productbuydistributorcompany',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductNutrition',
            fields=[
                ('pid', models.OneToOneField(db_column='PID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='myapp.product')),
                ('vitamin', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'product_nutrition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resultnutritionvalue',
            fields=[
                ('resultid', models.OneToOneField(db_column='ResultID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='myapp.samplingresult')),
                ('vitamin', models.CharField(db_column='VITAMIN', max_length=100)),
                ('amount', models.DecimalField(db_column='AMOUNT', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'resultnutritionvalue',
                'managed': False,
            },
        ),
    ]
